import React, { useState } from 'react';
import Header from '../src/componets/Header';
import './style.css';
import cow from "../src/cow.png";
import axios from 'axios';

function App() {
  const [initialText, changeInitialText] = useState('');
  const [reSubmissionText, changeReSubmissionText] = useState('');
  const [displayInfo, changeDisplay] = useState(false);
  const [profileData, setProfileData] = useState(null);
  const [percent, changePercent] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    const textToSend = displayInfo ? reSubmissionText : initialText;

    // Send the user's input to the Flask API\
    axios.post("http://localhost:5000/api",{"text":initialText})
  
      .then((response) => {
        const res = response.data;
        console.log(res)
        setProfileData({ reso: res.reso });
        changeDisplay(true)
      })
      .catch((error) => {
        if (error.response) {
          console.log(error.response);
          console.log(error.response.status);
          console.log(error.response.headers);
        }
      });
  }

  return (
    <div className="App">
      <Header />
      {!displayInfo ? (
        <div className="content">
          <div className="app-body">
            <img src={cow} alt="Cow" width="200px" height="200px" />
            <div className="input-section">
              <form onSubmit={(e) => handleSubmit(e)}>
                <textarea
                  rows="10"
                  cols="100"
                  className="input"
                  placeholder="Enter the bull shi..."
                  value={initialText}
                  onChange={(e) => changeInitialText(e.target.value)}
                />
              </form>
              <button type="submit" className="button" onClick={(e) => handleSubmit(e)}>
                  <b>Smell</b>
                </button>
            </div>
          </div>
          <div className="disclaimer">
            <p>This is 100% generated by OpenAi.</p>
          </div>
        </div>
      ) : (
        <div className='results'>
          <div className='Boxinput'> 
            <h1 className='title'>Was this Text Bias or Bull?</h1>
            <hr/>
            <textarea
              rows="35"
              cols="110"
              className="input"
              placeholder="Enter the bull shi..."
              value={reSubmissionText}
              onChange={(e) => changeReSubmissionText(e.target.value)}
            />
            <div className='center'>
              <button className="button" onClick={(e) => handleSubmit(e)}>
                <b>Re-Sniff</b>
              </button>
            </div>
          </div>
          <div className='Box'>
            <h1 className='title'>Results</h1>
            <hr/>
            <p style={{ color: 'white' }}>{profileData.reso}</p>

            
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
